#!/bin/bash
# Script to install and configure the latest version of auditd on Ubuntu 24.04 LTS
# auditd - Linux Audit Framework
# Author: Security Enhancement Project
# Date: 2025-10-31

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[+]${NC} $1"
}

print_error() {
    echo -e "${RED}[!]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[*]${NC} $1"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root (use sudo)"
   exit 1
fi

# Check if running on Ubuntu 24.04
if ! grep -q "Ubuntu" /etc/os-release || ! grep -q "24.04" /etc/os-release; then
    print_warning "This script is designed for Ubuntu 24.04 LTS"
    read -p "Do you want to continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

print_status "Starting auditd installation for Ubuntu 24.04 LTS"

# Update package lists
print_status "Updating package lists..."
apt update

# Install auditd and audispd-plugins
print_status "Installing auditd and related packages..."
apt install -y auditd audispd-plugins

# Check installed version
AUDITD_VERSION=$(auditd -V 2>&1 | head -n1)
print_status "Installed: $AUDITD_VERSION"

# Backup original configuration
print_status "Backing up original configuration files..."
if [ -f /etc/audit/auditd.conf ]; then
    cp /etc/audit/auditd.conf /etc/audit/auditd.conf.backup-$(date +%Y%m%d-%H%M%S)
fi
if [ -f /etc/audit/rules.d/audit.rules ]; then
    cp /etc/audit/rules.d/audit.rules /etc/audit/rules.d/audit.rules.backup-$(date +%Y%m%d-%H%M%S)
fi

# Configure auditd
print_status "Configuring auditd..."

# Update auditd.conf for better logging
cat > /etc/audit/auditd.conf <<'EOF'
# auditd.conf - Configuration for Ubuntu 24.04 LTS
# This file controls the configuration of the audit daemon

log_file = /var/log/audit/audit.log
log_format = ENRICHED
log_group = adm
priority_boost = 4
flush = INCREMENTAL_ASYNC
freq = 50
num_logs = 5
disp_qos = lossy
dispatcher = /sbin/audispd
name_format = HOSTNAME
max_log_file = 8
max_log_file_action = ROTATE
space_left = 75
space_left_action = SYSLOG
verify_email = yes
action_mail_acct = root
admin_space_left = 50
admin_space_left_action = SUSPEND
disk_full_action = SUSPEND
disk_error_action = SUSPEND
use_libwrap = yes
tcp_listen_queue = 5
tcp_max_per_addr = 1
tcp_client_max_idle = 0
enable_krb5 = no
krb5_principal = auditd
EOF

# Create basic audit rules
print_status "Setting up basic audit rules..."

cat > /etc/audit/rules.d/audit.rules <<'EOF'
# auditd rules for Ubuntu 24.04 LTS
# Generated by Security Enhancement Project

# Remove any existing rules
-D

# Buffer Size
-b 8192

# Failure Mode (0=silent 1=printk 2=panic)
-f 1

# === Basic System Monitoring ===

# Monitor changes to system time
-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change
-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change
-a always,exit -F arch=b64 -S clock_settime -k time-change
-a always,exit -F arch=b32 -S clock_settime -k time-change
-w /etc/localtime -p wa -k time-change

# Monitor user/group information
-w /etc/group -p wa -k identity
-w /etc/passwd -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity

# Monitor network environment
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale
-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale
-w /etc/issue -p wa -k system-locale
-w /etc/issue.net -p wa -k system-locale
-w /etc/hosts -p wa -k system-locale
-w /etc/network -p wa -k system-locale
-w /etc/netplan -p wa -k system-locale

# Monitor SELinux/AppArmor events
-w /etc/apparmor/ -p wa -k MAC-policy
-w /etc/apparmor.d/ -p wa -k MAC-policy

# Monitor login/logout events
-w /var/log/faillog -p wa -k logins
-w /var/log/lastlog -p wa -k logins
-w /var/log/tallylog -p wa -k logins

# Monitor session initiation
-w /var/run/utmp -p wa -k session
-w /var/log/wtmp -p wa -k logins
-w /var/log/btmp -p wa -k logins

# Monitor discretionary access control permission changes
-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod

# Monitor unauthorized access attempts
-a always,exit -F arch=b64 -S open -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S open -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b64 -S open -S openat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S open -S openat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access

# Monitor privileged commands
-a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-passwd
-a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-sudo
-a always,exit -F path=/usr/bin/su -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-su
-a always,exit -F path=/usr/bin/chsh -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-chsh
-a always,exit -F path=/usr/bin/chage -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-chage

# Monitor file deletion events
-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete
-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete

# Monitor sudoers configuration
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers

# Monitor kernel module operations
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules

# Monitor SSH configuration
-w /etc/ssh/sshd_config -p wa -k sshd_config

# Monitor cron jobs
-w /etc/cron.allow -p wa -k cron
-w /etc/cron.deny -p wa -k cron
-w /etc/cron.d/ -p wa -k cron
-w /etc/cron.daily/ -p wa -k cron
-w /etc/cron.hourly/ -p wa -k cron
-w /etc/cron.monthly/ -p wa -k cron
-w /etc/cron.weekly/ -p wa -k cron
-w /etc/crontab -p wa -k cron
-w /var/spool/cron/crontabs/ -p wa -k cron

# Monitor system startup scripts
-w /etc/init.d/ -p wa -k init
-w /etc/init/ -p wa -k init
-w /etc/systemd/ -p wa -k systemd

# Monitor library loading
-a always,exit -F arch=b64 -S chmod -F auid>=1000 -F auid!=4294967295 -k perm_mod

# Make the configuration immutable (comment out if you need to modify rules later)
-e 2
EOF

# Load audit rules
print_status "Loading audit rules..."
augenrules --load

# Enable and start auditd service
print_status "Enabling and starting auditd service..."
systemctl enable auditd
systemctl start auditd

# Verify auditd is running
print_status "Verifying auditd service status..."
if systemctl is-active --quiet auditd; then
    print_status "auditd is running successfully"
else
    print_error "auditd failed to start"
    systemctl status auditd
    exit 1
fi

# Display audit rules
print_status "Current audit rules:"
auditctl -l | head -n 20

# Create a simple monitoring script
print_status "Creating audit monitoring helper script..."
cat > /usr/local/bin/audit-monitor <<'MONITOR_EOF'
#!/bin/bash
# Simple script to monitor audit logs

case "$1" in
    summary)
        echo "=== Audit Summary ==="
        aureport -au
        ;;
    logins)
        echo "=== Failed Login Attempts ==="
        aureport -l --failed
        ;;
    files)
        echo "=== File Access Events ==="
        ausearch -k access -i | tail -n 50
        ;;
    users)
        echo "=== User Actions ==="
        aureport -u
        ;;
    commands)
        echo "=== Executed Commands ==="
        ausearch -k privileged-sudo -i | tail -n 20
        ;;
    modifications)
        echo "=== System Modifications ==="
        ausearch -k perm_mod -i | tail -n 20
        ;;
    *)
        echo "Usage: audit-monitor {summary|logins|files|users|commands|modifications}"
        echo ""
        echo "  summary       - Show audit summary"
        echo "  logins        - Show failed login attempts"
        echo "  files         - Show file access events"
        echo "  users         - Show user actions"
        echo "  commands      - Show privileged commands"
        echo "  modifications - Show system modifications"
        exit 1
        ;;
esac
MONITOR_EOF

chmod +x /usr/local/bin/audit-monitor

# Installation complete
print_status "================================================"
print_status "auditd installation completed successfully!"
print_status "================================================"
echo ""
print_status "Service Status:"
systemctl status auditd --no-pager | grep -E "Active:|Loaded:"
echo ""
print_status "Useful Commands:"
echo "  - View audit logs: ausearch -i"
echo "  - Generate report: aureport"
echo "  - Monitor events: audit-monitor summary"
echo "  - Check rules: auditctl -l"
echo "  - Service status: systemctl status auditd"
echo ""
print_status "Log files location: /var/log/audit/"
echo ""
print_warning "Note: Audit rules are set to immutable mode (-e 2)"
print_warning "To modify rules, you need to reboot or edit /etc/audit/rules.d/audit.rules"
echo ""
print_status "Documentation: man auditd, man aureport, man ausearch"
print_status "Monitor script: audit-monitor"
